name: Smoke
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - run: echo "hi"
  Smoke:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup go env 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Smoke
        run: |
          cd "src/alation/scarlet"
          make depend
          make generate
          make unit
          make lint
          make build_dev
